### ISSUE TITLE
Partner's programs?

### ISSUE THREAD

**Issue by kcgthb** [nwchemgit/nwchemgit.github.io#1]
Hi!

It looks like the NWChem website at https://www.nwchem-sw.org/ is promoting spyware:
> **We recommend that you try our partner's programs**
> * REFOG Personal Monitor is one of the most powerful [keylogger](https://www.refog.com/keylogger.html) software designed for remote computer monitoring. You can also use this multi-functional software to monitor employees or use it for parental control on a Windows-operated PC.
> * Hoverwatch is an advanced [mobile tracker](https://www.hoverwatch.com/) for Android. This app also has a free trial version with certain functional limitations. Hoverwatch will help you monitor your kids' phones to protect them from the disclosure of confidential data and sensitive information to strangers, and avoid terrible consequences for you and your family.

![image](https://user-images.githubusercontent.com/186807/165170873-471b880e-d9bb-4065-9098-f11c5bc6a603.png)

This "partner's program" section doesn't seem to be present in the [source page](https://github.com/nwchemgit/nwchemgit.github.io/blob/master/index.html) (although it refers to an older NWChem version, so it may not be up to date).

Is this legit?

**Comment by edoapra** [comment]
No,  https://www.nwchem-sw.org/  is not a legitimate NWChem website

**Comment by kcgthb** [comment]
Thanks!
And interesting. You may want to do something about it, because it's the 1st hit on Google:

![image](https://user-images.githubusercontent.com/186807/165173959-29e5ce61-5e38-45da-b733-3871329bf2a2.png)
